import { BadgeMeta } from '../abi/DevTechABI';

export type BadgeStatus = 'earned' | 'available' | 'locked';

interface BadgeCardProps {
    badge: BadgeMeta;
    status: BadgeStatus;
    onMint?: () => void;
    minting?: boolean;
}

const BADGE_IMG: Record<number, string> = {};
for (let i = 1; i <= 15; i++) {
    // Use SVG badges (PNG equivalents generated by badges/generate_badges.mjs if OPENAI_API_KEY set)
    BADGE_IMG[i] = `/badges/badge_${String(i).padStart(2, '0')}.svg`;
}

export function BadgeCard({ badge, status, onMint, minting }: BadgeCardProps) {
    const opacity = status === 'locked' ? 0.4 : 1;
    const glow    = status === 'earned'    ? `0 0 20px ${badge.color}40` : 'none';

    return (
        <div style={{
            background: '#0f1117',
            border: `1px solid ${status === 'earned' ? badge.color + '50' : 'rgba(255,255,255,0.06)'}`,
            borderRadius: '12px',
            padding: '14px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '8px',
            opacity,
            boxShadow: glow,
            transition: 'all 0.2s',
            position: 'relative',
        }}>
            {/* Badge image */}
            <div style={{ width: '140px', height: '140px', borderRadius: '50%', overflow: 'hidden', border: `2px solid ${badge.color}40`, flexShrink: 0 }}>
                <img
                    src={BADGE_IMG[badge.id] ?? ''}
                    alt={badge.name}
                    style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    onError={(e) => {
                        (e.currentTarget as HTMLImageElement).style.display = 'none';
                    }}
                />
                {/* SVG fallback behind image */}
                <div style={{ position: 'absolute', top: '14px', left: '50%', transform: 'translateX(-50%)', width: '140px', height: '140px', borderRadius: '50%', background: `${badge.color}15`, display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: -1 }}>
                    <span style={{ color: badge.color, fontFamily: 'monospace', fontWeight: 700, fontSize: '14px' }}>
                        {badge.id}
                    </span>
                </div>
            </div>

            {/* Track tag */}
            <span style={{ fontSize: '10px', padding: '2px 9px', border: `1px solid ${badge.color}40`, borderRadius: '4px', color: badge.color, fontFamily: 'monospace', letterSpacing: '0.08em', fontWeight: 700 }}>
                {badge.track.toUpperCase()}
            </span>

            {/* Name */}
            <div style={{ fontFamily: 'Courier New, monospace', fontSize: '13px', fontWeight: 700, color: '#e2e8f0', textAlign: 'center', lineHeight: 1.3 }}>
                {badge.name}
            </div>

            {/* Requirement */}
            <div style={{ fontSize: '10px', color: '#6b7280', textAlign: 'center', fontFamily: 'monospace', lineHeight: 1.4, minHeight: '28px' }}>
                {badge.requirement}
            </div>

            {/* Score */}
            <div style={{ fontSize: '12px', fontWeight: 700, color: badge.color, fontFamily: 'monospace' }}>
                +{badge.score} pts
            </div>

            {/* Status badge / Mint button */}
            {status === 'earned' && (
                <div style={{ padding: '4px 10px', background: `${badge.color}15`, border: `1px solid ${badge.color}40`, borderRadius: '6px', fontSize: '9px', color: badge.color, fontFamily: 'monospace', fontWeight: 700 }}>
                    EARNED
                </div>
            )}
            {status === 'available' && (
                <button
                    onClick={onMint}
                    disabled={minting}
                    style={{
                        width: '100%', padding: '6px', borderRadius: '6px',
                        background: minting ? 'rgba(255,255,255,0.05)' : `${badge.color}20`,
                        border: `1px solid ${badge.color}50`,
                        color: minting ? '#6b7280' : badge.color,
                        fontFamily: 'Courier New, monospace', fontSize: '10px', fontWeight: 700,
                        cursor: minting ? 'not-allowed' : 'pointer', letterSpacing: '0.05em',
                    }}
                >
                    {minting ? 'MINTING...' : 'MINT BADGE'}
                </button>
            )}
            {status === 'locked' && (
                <div style={{ fontSize: '9px', color: '#4b5563', fontFamily: 'monospace' }}>
                    LOCKED
                </div>
            )}
        </div>
    );
}
